// Generated by MSXDEVStudio — do not edit by hand.
// Edit the source resource and re-export (or press Build) instead.
//
// Generation parameters:
//  - Source: res/background.map.json
//  - Compression: RLEp (MSXgl "compress" module — unpack with RLEp_UnpackToRAM)
//  - Tileset: res/tiles.tiles.json
//  - Size: 32×24
//  - Layers: sky

#pragma once

#define G_BACKGROUNDMAP_W 32
#define G_BACKGROUNDMAP_H 24

#define G_BACKGROUNDMAP_SKY_SIZE 361
#define G_BACKGROUNDMAP_SKY_UNPACKED_SIZE 768
extern const unsigned char g_BackgroundMap_Sky[];
