// Generated by MSXStudio — do not edit by hand.
// Edit the source resource and re-export (or press Build) instead.
//
// Generation parameters:
//  - Source: res/intro.map.json
//  - Tileset: res/intro.tiles.json
//  - Size: 32×24
//  - Layers: background

#pragma once

#define G_INTROMAP_W 32
#define G_INTROMAP_H 24

#define G_INTROMAP_BACKGROUND_SIZE 768
extern const unsigned char g_IntroMap_Background[];
