// Generated by MSXStudio — do not edit by hand.
// Edit the source resource and re-export (or press Build) instead.
//
// Generation parameters:
//  - Source: res/intro.tiles.json
//  - Mode: SCREEN 2 (GRAPHIC 2)
//  - Tiles: 256
//  - Blocks: App_logo 9×2, demo_game 5×1, press_space 11×1

#pragma once

#define G_INTROTILES_APP_LOGO_BASE 0
#define G_INTROTILES_APP_LOGO_W 9
#define G_INTROTILES_APP_LOGO_H 2
#define G_INTROTILES_DEMO_GAME_BASE 18
#define G_INTROTILES_DEMO_GAME_W 5
#define G_INTROTILES_DEMO_GAME_H 1
#define G_INTROTILES_PRESS_SPACE_BASE 23
#define G_INTROTILES_PRESS_SPACE_W 11
#define G_INTROTILES_PRESS_SPACE_H 1

#define G_INTROTILES_PATTERNS_SIZE 2048
extern const unsigned char g_IntroTiles_Patterns[];

#define G_INTROTILES_COLORS_SIZE 2048
extern const unsigned char g_IntroTiles_Colors[];

#define G_INTROTILES_BLOCKS_SIZE 34
extern const unsigned char g_IntroTiles_Blocks[];
