// Generated by MSXDEVStudio — do not edit by hand.
// Edit the source resource and re-export (or press Build) instead.
//
// Generation parameters:
//  - Source: res/level.map.json
//  - Compression: RLEp (MSXgl "compress" module — unpack with RLEp_UnpackToRAM)
//  - Tileset: res/tiles.tiles.json
//  - Size: 64×12
//  - Layers: background

#pragma once

#define G_LEVELMAP_W 64
#define G_LEVELMAP_H 12

#define G_LEVELMAP_BACKGROUND_SIZE 242
#define G_LEVELMAP_BACKGROUND_UNPACKED_SIZE 768
extern const unsigned char g_LevelMap_Background[];
