// Generated by MSXDEVStudio — do not edit by hand.
// Edit the source resource and re-export (or press Build) instead.
//
// Generation parameters:
//  - Source: res/sfx.sfx.json
//  - Format: ayFX bank (play with MSXgl LibModules "ayfx/ayfx_player")
//  - Effects: 0=coin, 1=jump, 2=win
//  - Replay rate: 50 Hz

#pragma once

#define G_SFX_SIZE 76
extern const unsigned char g_Sfx[];
