/**
 * Emits MSXgl-style C headers (and raw binaries) from editor resources,
 * following the conventions of MSXimg's own output — a comment block naming
 * the generation parameters, `const unsigned char g_Name[] = { … };` tables,
 * per-byte ASCII art for 1-bit pattern data, and a size comment per table.
 *
 * Deterministic by construction: **no dates, no absolute paths**, so a
 * re-export with unchanged input produces byte-identical output and the
 * mtime-based build skip actually skips.
 */

export interface EmitTable {
  /** Appended to the base name (`'_Patterns'` → `g_MyTiles_Patterns`). Empty = the base name alone. */
  suffix: string
  bytes: Uint8Array
  /** Render one byte per line with a `/⁠* ######.. *⁠/` bit picture — for pattern tables. */
  art?: boolean
  /** Bytes per line when `art` is off. */
  perLine?: number
  /** Placed above the table as a `// …` line. */
  comment?: string
  /**
   * Set when `bytes` is compressed: the size it unpacks to, emitted as
   * `<NAME>_UNPACKED_SIZE` so the game can size the buffer it unpacks into.
   * `<NAME>_SIZE` stays what it always was — the length of the table itself.
   */
  unpacked?: number
}

export interface EmitOptions {
  /** Base table name, MSXgl convention `g_Something`. */
  name: string
  tables: EmitTable[]
  /** Extra `//  - Key: value` lines in the parameter block. */
  notes?: string[]
  /** Also emit `#define <NAME>_SIZE …` for each table. */
  defines?: boolean
  /** Extra `#define`s emitted before the tables, as raw `#define NAME value` lines. */
  constants?: string[]
  /** Ready-made C: what belongs in the header, and what belongs in the source. */
  code?: HelperC
  /** File name of the header, so the generated `.c` can include it. */
  headerFile?: string
}

/**
 * A generated helper, split the way C requires once a project spans more than
 * one file: types and prototypes in the header, bodies in the source. Emitting
 * the bodies into the header instead would force `static`, and every module
 * that included it would get its own copy plus an "unused" warning.
 */
export interface HelperC {
  header: string[]
  source: string[]
}

const BANNER = [
  '// Generated by MSXDEVStudio — do not edit by hand.',
  '// Edit the source resource and re-export (or press Build) instead.'
]

function hex(value: number): string {
  return `0x${value.toString(16).toUpperCase().padStart(2, '0')}`
}

function art(value: number): string {
  let out = ''
  for (let bit = 7; bit >= 0; bit--) out += value & (1 << bit) ? '#' : '.'
  return out
}

/** Uppercase, C-identifier-safe form of a table name, for `#define`s. */
export function defineName(name: string): string {
  return name.replace(/[^A-Za-z0-9]/g, '_').toUpperCase()
}

function emitTable(name: string, table: EmitTable): string[] {
  const lines: string[] = []
  if (table.comment) lines.push(`// ${table.comment}`)
  lines.push(`const unsigned char ${name}[] =`, '{')
  if (table.art) {
    for (const value of table.bytes) lines.push(`\t${hex(value)}, /* ${art(value)} */`)
  } else {
    const perLine = table.perLine ?? 16
    for (let i = 0; i < table.bytes.length; i += perLine) {
      lines.push(`\t${[...table.bytes.subarray(i, i + perLine)].map(hex).join(', ')},`)
    }
  }
  lines.push('};', `// ${name} size: ${table.bytes.length} Bytes`, '')
  return lines
}

/**
 * The two halves of a C export.
 *
 * The header declares — sizes, offsets, `extern` tables, helper prototypes —
 * and the source defines. That split is what lets a project be more than one
 * `.c`: a table *defined* in a header is a duplicate symbol the moment a second
 * module includes it, which is a link error rather than a warning.
 */
export function emitC(options: EmitOptions): { header: string; source: string } {
  const head = [...BANNER]
  if (options.notes?.length) {
    head.push('//', '// Generation parameters:')
    for (const note of options.notes) head.push(`//  - ${note}`)
  }
  head.push('', '#pragma once', '')
  if (options.constants?.length) head.push(...options.constants, '')

  const body = [...BANNER, '']
  // The helpers call into MSXgl and their prototypes use its types, so the
  // source that defines them needs the engine's header — it is compiled on its
  // own, not pasted into a file that already included it.
  if (options.code?.source.length) body.push('#include "msxgl.h"')
  if (options.headerFile) body.push(`#include "${options.headerFile}"`, '')

  let total = 0
  for (const table of options.tables) {
    const name = `${options.name}${table.suffix}`
    if (options.defines) {
      head.push(`#define ${defineName(name)}_SIZE ${table.bytes.length}`)
      if (table.unpacked !== undefined) head.push(`#define ${defineName(name)}_UNPACKED_SIZE ${table.unpacked}`)
    }
    head.push(`extern const unsigned char ${name}[];`, '')
    body.push(...emitTable(name, table))
    total += table.bytes.length
  }
  if (options.tables.length > 1) body.push(`// Total size: ${total} Bytes`)
  if (options.code) {
    head.push(...options.code.header)
    body.push(...options.code.source)
  }
  const finish = (lines: string[]): string => `${lines.join('\n').replace(/\n+$/, '')}\n`
  return { header: finish(head), source: finish(body) }
}

/** The same tables as one raw blob, concatenated in order — the `format: "bin"` export. */
export function emitBin(tables: readonly EmitTable[]): Uint8Array {
  const total = tables.reduce((sum, table) => sum + table.bytes.length, 0)
  const out = new Uint8Array(total)
  let offset = 0
  for (const table of tables) {
    out.set(table.bytes, offset)
    offset += table.bytes.length
  }
  return out
}
