/**
 * Emits MSXgl-style C headers (and raw binaries) from editor resources,
 * following the conventions of MSXimg's own output — a comment block naming
 * the generation parameters, `const unsigned char g_Name[] = { … };` tables,
 * per-byte ASCII art for 1-bit pattern data, and a size comment per table.
 *
 * Deterministic by construction: **no dates, no absolute paths**, so a
 * re-export with unchanged input produces byte-identical output and the
 * mtime-based build skip actually skips.
 */

export interface EmitTable {
  /** Appended to the base name (`'_Patterns'` → `g_MyTiles_Patterns`). Empty = the base name alone. */
  suffix: string
  bytes: Uint8Array
  /** Render one byte per line with a `/⁠* ######.. *⁠/` bit picture — for pattern tables. */
  art?: boolean
  /** Bytes per line when `art` is off. */
  perLine?: number
  /** Placed above the table as a `// …` line. */
  comment?: string
  /**
   * Set when `bytes` is compressed: the size it unpacks to, emitted as
   * `<NAME>_UNPACKED_SIZE` so the game can size the buffer it unpacks into.
   * `<NAME>_SIZE` stays what it always was — the length of the table itself.
   */
  unpacked?: number
}

export interface EmitOptions {
  /** Base table name, MSXgl convention `g_Something`. */
  name: string
  tables: EmitTable[]
  /** Extra `//  - Key: value` lines in the parameter block. */
  notes?: string[]
  /** Also emit `#define <NAME>_SIZE …` for each table. */
  defines?: boolean
  /** Extra `#define`s emitted before the tables, as raw `#define NAME value` lines. */
  constants?: string[]
  /** Ready-made C appended after the tables — the opt-in helpers, verbatim. */
  code?: string[]
}

const BANNER = [
  '// Generated by MSXStudio — do not edit by hand.',
  '// Edit the source resource and re-export (or press Build) instead.'
]

function hex(value: number): string {
  return `0x${value.toString(16).toUpperCase().padStart(2, '0')}`
}

function art(value: number): string {
  let out = ''
  for (let bit = 7; bit >= 0; bit--) out += value & (1 << bit) ? '#' : '.'
  return out
}

/** Uppercase, C-identifier-safe form of a table name, for `#define`s. */
export function defineName(name: string): string {
  return name.replace(/[^A-Za-z0-9]/g, '_').toUpperCase()
}

function emitTable(name: string, table: EmitTable): string[] {
  const lines: string[] = []
  if (table.comment) lines.push(`// ${table.comment}`)
  lines.push(`const unsigned char ${name}[] =`, '{')
  if (table.art) {
    for (const value of table.bytes) lines.push(`\t${hex(value)}, /* ${art(value)} */`)
  } else {
    const perLine = table.perLine ?? 16
    for (let i = 0; i < table.bytes.length; i += perLine) {
      lines.push(`\t${[...table.bytes.subarray(i, i + perLine)].map(hex).join(', ')},`)
    }
  }
  lines.push('};', `// ${name} size: ${table.bytes.length} Bytes`, '')
  return lines
}

export function emitCHeader(options: EmitOptions): string {
  const lines = [...BANNER]
  if (options.notes?.length) {
    lines.push('//', '// Generation parameters:')
    for (const note of options.notes) lines.push(`//  - ${note}`)
  }
  lines.push('')
  if (options.constants?.length) lines.push(...options.constants, '')

  let total = 0
  for (const table of options.tables) {
    const name = `${options.name}${table.suffix}`
    if (options.defines) {
      lines.push(`#define ${defineName(name)}_SIZE ${table.bytes.length}`)
      if (table.unpacked !== undefined) lines.push(`#define ${defineName(name)}_UNPACKED_SIZE ${table.unpacked}`)
      lines.push('')
    }
    lines.push(...emitTable(name, table))
    total += table.bytes.length
  }
  if (options.tables.length > 1) lines.push(`// Total size: ${total} Bytes`)
  if (options.code?.length) lines.push(...options.code)
  return `${lines.join('\n').replace(/\n+$/, '')}\n`
}

/** The same tables as one raw blob, concatenated in order — the `format: "bin"` export. */
export function emitBin(tables: readonly EmitTable[]): Uint8Array {
  const total = tables.reduce((sum, table) => sum + table.bytes.length, 0)
  const out = new Uint8Array(total)
  let offset = 0
  for (const table of tables) {
    out.set(table.bytes, offset)
    offset += table.bytes.length
  }
  return out
}
