import js from '@eslint/js'
import pluginVue from 'eslint-plugin-vue'
import { withVueTs, vueTsConfigs } from '@vue/eslint-config-typescript'
import globals from 'globals'

export default withVueTs(
  // demo_project/ is an MSX game, not part of the app: its project_config.js is
  // generated by MSXStudio and assigns MSXgl's globals, which no-undef rejects.
  // The demo projects are MSX game source, not app source: their `.js` is
  // MSXgl's generated config, whose globals are set by MSXgl's build tool.
  // The demo projects are MSX C and MSXgl build config, not repo JavaScript —
  // `project_config.js` is a script MSXgl evaluates with its own globals.
  { ignores: ['**/node_modules/**', '**/dist/**', '**/out/**', 'demo_msx1/**', 'demo2_project/**'] },
  js.configs.recommended,
  pluginVue.configs['flat/recommended'],
  vueTsConfigs.recommended,
  {
    languageOptions: {
      globals: { ...globals.node, ...globals.browser }
    },
    rules: {
      'vue/multi-word-component-names': 'off'
    }
  }
)
