import js from '@eslint/js'
import pluginVue from 'eslint-plugin-vue'
import { withVueTs, vueTsConfigs } from '@vue/eslint-config-typescript'
import globals from 'globals'

export default withVueTs(
  // demo_project/ is an MSX game, not part of the app: its project_config.js is
  // generated by MSXStudio and assigns MSXgl's globals, which no-undef rejects.
  { ignores: ['**/node_modules/**', '**/dist/**', '**/out/**', 'demo_project/**'] },
  js.configs.recommended,
  pluginVue.configs['flat/recommended'],
  vueTsConfigs.recommended,
  {
    languageOptions: {
      globals: { ...globals.node, ...globals.browser }
    },
    rules: {
      'vue/multi-word-component-names': 'off'
    }
  }
)
