// Generated by MSXStudio — do not edit by hand.
// Edit the source resource and re-export (or press Build) instead.
//
// Generation parameters:
//  - Source: res/mist.screen.json
//  - Mode: SCREEN 5 (GRAPHIC 4)
//  - Dither: none
//  - Fragments: wide 48×16, small 32×16, long 40×16

#pragma once

#define G_MIST_W 120
#define G_MIST_H 16
#define G_MIST_STRIP_W 120
#define G_MIST_STRIP_H 16
#define G_MIST_BACKUP_PITCH 52
#define G_MIST_WIDE 0
#define G_MIST_SMALL 1
#define G_MIST_LONG 2

#define G_MIST_PALETTE_SIZE 32
extern const unsigned char g_Mist_Palette[];

#define G_MIST_STRIP_SIZE 960
extern const unsigned char g_Mist_Strip[];

#define G_MIST_RECTS_SIZE 12
extern const unsigned char g_Mist_Rects[];


// ── g_Mist: software sprites ─────────────────────────────────────────
//
// Software sprites are drawn *into* the screen, so they escape the VDP's
// 4/8-sprites-per-line limit — at the price of putting back what they
// covered. The frames live side by side in g_Mist_Strip; upload it once
// into VRAM the screen never shows (below the visible lines is the usual
// spot), then move each object with Restore/Draw.
//
// Needs MSXgl's VDP command engine: MSX2 or later with VDP_USE_COMMAND,
// and "msxgl.h" included before this header.
//
// Two rules:
//  - Give every object its own slot (0, 1, 2 …). Backgrounds are saved
//    side by side in the row under the strip, G_MIST_BACKUP_PITCH dots apart,
//    and two objects sharing a slot would eat each other's background.
//  - When objects can overlap, Restore them all in *reverse* draw order
//    first, then Draw them all in order. Restoring one at a time rubs out
//    whatever was drawn on top of it.
//
// Example:
//   g_Mist_Upload(212);                  // strip parked at VRAM row 212
//   g_Mist_SwSprite hero = { 0 };        // slot 0
//   // every frame:
//   g_Mist_Restore(&hero, 212);
//   g_Mist_Draw(&hero, G_MIST_WIDE, x, y, 212);
typedef struct
{
	u8  slot; // which backup column this object owns
	UX  bx;   // the saved background rectangle; bw = 0 means nothing is on screen
	UY  by;
	u8  bw, bh;
} g_Mist_SwSprite;

void g_Mist_Upload(UY stripY);
void g_Mist_Restore(g_Mist_SwSprite* s, UY stripY);
void g_Mist_Draw(g_Mist_SwSprite* s, u8 frame, UX x, UY y, UY stripY);
