// Generated by MSXStudio — do not edit by hand.
// Edit the source resource and re-export (or press Build) instead.
//
// Generation parameters:
//  - Source: res/sfx.sfx.json
//  - Format: ayFX bank (play with MSXgl LibModules "ayfx/ayfx_player")
//  - Effects: 0=shoot, 1=boom, 2=crash, 3=hit, 4=victory
//  - Replay rate: 50 Hz

#pragma once

#define G_SFX_SIZE 215
extern const unsigned char g_Sfx[];
