/**
 * Installing the bundled demo projects into a folder the user picks.
 *
 * The demos ship as **plain files beside the asar** (`extraResources`), not
 * inside it, so this is an ordinary recursive copy with no asar read semantics
 * in the way. They are copied *out* rather than opened in place because a build
 * writes `out/` into the project folder, and the install directory is
 * root-owned on Linux and under Program Files on Windows — a demo left there
 * could be read but never run.
 *
 * Electron-free, same split as `project.ts` and `examples.ts`: everything
 * testable lives here and `index.ts` only wires the dialog and the IPC.
 */

import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, sep } from 'node:path'

export interface DemoProject {
  /** Folder name, in the repo and in `resources/demos/` alike. */
  id: string
  title: string
  /** The `.msxproj` to open once it is installed. */
  projectFile: string
  blurb: string
}

export const DEMO_PROJECTS: DemoProject[] = [
  {
    id: 'demo_msx1',
    title: 'Demo 1 — a two-screen MSX1 platformer',
    projectFile: 'demo.msxproj',
    blurb: 'A SCREEN 2 tileset, a six-pose sprite, a 64x24 map and an ayFX bank, in a 32 KB ROM.'
  },
  {
    id: 'demo_msx2',
    title: 'Demo 2 — Canyon Runner, an MSX2 vertical shooter',
    projectFile: 'canyon.msxproj',
    blurb: 'SCREEN 5 in a 128 KB MegaROM: hardware scrolling, sprite mode 2, software sprites.'
  }
]

/**
 * Build output and IDE state — regenerated by the first build, and never worth
 * carrying. Excluded at *both* ends: `electron-builder.yml` keeps them out of
 * the package, and the copy below keeps them out of a dev-mode install, whose
 * source is the working tree and does have them.
 *
 * Shipping `out/` would also mean shipping a prebuilt ROM, which could let a
 * demo look like it ran on a machine whose toolchain is actually broken.
 */
export const EXCLUDED_DIRS = ['out', 'emul', 'node_modules', '.msxdevstudio']

/** Written into each installed copy, so a stale demo is diagnosable later. */
export const STAMP_FILE = '.msxdevstudio-demo.json'

/**
 * Where the pristine demos are at runtime.
 *
 * Packaged, they are `extraResources` under `resources/demos/`. In development
 * there is no such folder, and the originals are simply the repo's own
 * `demo_msx1/` and `demo_msx2/` — which is `app.getAppPath()`. Either way a
 * demo is `<root>/<id>`, so nothing downstream has to care which it was.
 */
export function demosRoot(packaged: boolean, appPath: string, resourcesPath: string): string {
  return packaged ? join(resourcesPath, 'demos') : appPath
}

/**
 * Whether a path inside a demo folder should be copied. `relative` is the path
 * relative to the demo's own root, in either separator.
 */
export function shouldCopy(relative: string): boolean {
  if (relative === '') return true
  const segments = relative.split(/[/\\]/)
  return !segments.some((segment) => EXCLUDED_DIRS.includes(segment))
}

export interface DemoPlanEntry {
  demo: DemoProject
  source: string
  destination: string
  /** The source folder is present — false means this build shipped without it. */
  available: boolean
  /** Something is already at `destination`; installing would overwrite it. */
  conflict: boolean
}

/** What installing into `targetDir` would do, without doing any of it. */
export function planInstall(sourceRoot: string, targetDir: string): DemoPlanEntry[] {
  return DEMO_PROJECTS.map((demo) => {
    const source = join(sourceRoot, demo.id)
    const destination = join(targetDir, demo.id)
    return {
      demo,
      source,
      destination,
      available: existsSync(source),
      conflict: existsSync(destination)
    }
  })
}

export interface InstallResult {
  /** Absolute paths of the demos that were written. */
  installed: { id: string; path: string; projectFile: string }[]
  /** Ids left alone because something was already there and `overwrite` was false. */
  conflicts: string[]
  /** Ids this build did not ship. Empty in any normal build. */
  missing: string[]
}

/**
 * Copies every available demo into `targetDir`.
 *
 * Conflicts are reported rather than resolved: with `overwrite` false, an
 * entry whose destination exists is skipped and named in `conflicts`, so the
 * caller can ask before anything is touched. Nothing else is destructive —
 * `cpSync` merges into an existing tree rather than clearing it first, which
 * is what keeps a re-install from deleting work sitting beside the demo.
 */
export function installDemos(
  sourceRoot: string,
  targetDir: string,
  options: { overwrite?: boolean; version?: string } = {}
): InstallResult {
  const result: InstallResult = { installed: [], conflicts: [], missing: [] }
  mkdirSync(targetDir, { recursive: true })

  for (const entry of planInstall(sourceRoot, targetDir)) {
    if (!entry.available) {
      result.missing.push(entry.demo.id)
      continue
    }
    if (entry.conflict && !options.overwrite) {
      result.conflicts.push(entry.demo.id)
      continue
    }

    cpSync(entry.source, entry.destination, {
      recursive: true,
      // `cpSync` hands the filter absolute paths; the exclusions are about a
      // path's position *inside the demo*, so compare on that.
      filter: (src) => shouldCopy(src.slice(entry.source.length).replace(/^[/\\]/, ''))
    })
    writeStamp(entry.destination, entry.demo.id, options.version)

    result.installed.push({
      id: entry.demo.id,
      path: entry.destination,
      projectFile: join(entry.destination, entry.demo.projectFile)
    })
  }

  return result
}

function writeStamp(destination: string, id: string, version?: string): void {
  const stamp = { demo: id, msxdevstudio: version ?? 'unknown' }
  writeFileSync(join(destination, STAMP_FILE), `${JSON.stringify(stamp, null, 2)}\n`, 'utf-8')
}

/** The MSXDEVStudio version an installed copy came from, or null if unstamped. */
export function installedVersion(demoDir: string): string | null {
  const file = join(demoDir, STAMP_FILE)
  if (!existsSync(file)) return null
  try {
    const parsed = JSON.parse(readFileSync(file, 'utf-8')) as { msxdevstudio?: unknown }
    return typeof parsed.msxdevstudio === 'string' ? parsed.msxdevstudio : null
  } catch {
    return null // hand-edited or truncated; not worth failing an install over
  }
}

/** `<targetDir>` shown to the user after an install, with a trailing separator. */
export function displayTarget(targetDir: string): string {
  return targetDir.endsWith(sep) ? targetDir : targetDir + sep
}
