import { spawnSync } from 'node:child_process'
import { cpSync, existsSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { REAL_MSXGL, hasMsxgl, scratchRoot } from './__fixtures__/msxgl'
import {
  createProject,
  evaluateProjectConfig,
  importProject,
  loadProject,
  resolveNodeBinary,
  readIdeState,
  saveProject,
  scanLibModules,
  writeIdeState
} from './project'

// The same real MSXgl checkout `toolchain.test.ts` uses. Never referenced from
// product code — ProjectService gets the root from ToolchainService.
const NODE = resolveNodeBinary(REAL_MSXGL)

const tmpDirs: string[] = []
function makeTmpDir(prefix: string): string {
  const dir = mkdtempSync(join(scratchRoot(), prefix))
  tmpDirs.push(dir)
  return dir
}

afterEach(() => {
  while (tmpDirs.length) {
    const dir = tmpDirs.pop()
    if (dir) rmSync(dir, { recursive: true, force: true })
  }
})

/** Nanosecond mtime — plain mtimeMs is too coarse to prove "this file was not rewritten". */
function mtimeNs(path: string): bigint {
  return statSync(path, { bigint: true }).mtimeNs
}

describe('createProject', () => {
  it.runIf(hasMsxgl)('scaffolds a complete, buildable project layout from the MSX1 template', () => {
    const location = makeTmpDir('msxproj-new-')
    const opened = createProject(
      { name: 'mygame', location, machine: '1', target: 'ROM_32K', libModules: ['system', 'bios', 'vdp'] },
      REAL_MSXGL
    )

    expect(opened.root).toBe(join(location, 'mygame'))
    expect(opened.projectFile).toBe('mygame.msxproj')
    for (const rel of ['main.c', 'msxgl_config.h', 'mygame.msxproj', 'project_config.js', 'content', '.gitignore', 'build.sh', 'build.bat']) {
      expect(existsSync(join(opened.root, rel)), rel).toBe(true)
    }

    // main.c is the template verbatim.
    expect(readFileSync(join(opened.root, 'main.c'), 'utf-8')).toBe(
      readFileSync(join(REAL_MSXGL, 'projects/template/template.c'), 'utf-8')
    )
    expect(readFileSync(join(opened.root, '.gitignore'), 'utf-8')).toBe('out/\nemul/\n.msxdevstudio/\n')

    const config = readFileSync(join(opened.root, 'project_config.js'), 'utf-8')
    expect(config).toContain('// GENERATED by MSXDEVStudio from mygame.msxproj')
    expect(config).toContain('ProjName = "mygame";')
    expect(config).toContain('LibModules = ["system", "bios", "vdp"];')

    // Launchers default to the configured MSXgl path but honour MSXGL_PATH.
    const sh = readFileSync(join(opened.root, 'build.sh'), 'utf-8')
    expect(sh).toContain(`MSXGL_PATH="\${MSXGL_PATH:-${REAL_MSXGL}}"`)
    expect(sh).toContain('engine/script/js/build.js')
    expect(statSync(join(opened.root, 'build.sh')).mode & 0o111).not.toBe(0)
    expect(readFileSync(join(opened.root, 'build.bat'), 'utf-8')).toContain('if not defined MSXGL_PATH set MSXGL_PATH=')
  })

  it.runIf(hasMsxgl)('uses the MSX2 template for machines above MSX1', () => {
    const location = makeTmpDir('msxproj-msx2-')
    const opened = createProject(
      { name: 'game2', location, machine: '2', target: 'ROM_32K', libModules: ['system'] },
      REAL_MSXGL
    )
    expect(readFileSync(join(opened.root, 'main.c'), 'utf-8')).toBe(
      readFileSync(join(REAL_MSXGL, 'projects/template_msx2/template.c'), 'utf-8')
    )
    expect(readFileSync(join(opened.root, 'project_config.js'), 'utf-8')).toContain('Machine = "2";')
  })

  it.runIf(hasMsxgl)('refuses to scaffold into a non-empty folder', () => {
    const location = makeTmpDir('msxproj-busy-')
    createProject({ name: 'once', location, machine: '1', target: 'ROM_32K', libModules: [] }, REAL_MSXGL)
    expect(() =>
      createProject({ name: 'once', location, machine: '1', target: 'ROM_32K', libModules: [] }, REAL_MSXGL)
    ).toThrow(/already exists/)
  })
})

describe('saveProject / loadProject', () => {
  it.runIf(hasMsxgl)('round-trips the .msxproj and regenerates project_config.js on every save', () => {
    const location = makeTmpDir('msxproj-save-')
    const opened = createProject(
      { name: 'rt', location, machine: '1', target: 'ROM_32K', libModules: ['system'] },
      REAL_MSXGL
    )

    const changed = { ...opened.project, target: 'ROM_ASCII8', romSize: 128 }
    saveProject(opened.root, opened.projectFile, changed)

    const reloaded = loadProject(opened.root)
    expect(reloaded?.project.target).toBe('ROM_ASCII8')
    expect(reloaded?.project.romSize).toBe(128)
    const config = readFileSync(join(opened.root, 'project_config.js'), 'utf-8')
    expect(config).toContain('Target = "ROM_ASCII8";')
    expect(config).toContain('ROMSize = 128;')
  })

  it.runIf(hasMsxgl)('never rewrites project_config.js when customConfig is set', () => {
    const location = makeTmpDir('msxproj-custom-')
    const opened = createProject(
      { name: 'custom', location, machine: '1', target: 'ROM_32K', libModules: ['system'] },
      REAL_MSXGL
    )
    const configPath = join(opened.root, 'project_config.js')
    writeFileSync(configPath, '// hand written\nProjName = "custom";\n', 'utf-8')
    const before = mtimeNs(configPath)

    saveProject(opened.root, opened.projectFile, { ...opened.project, customConfig: true, target: 'DOS2' })

    expect(mtimeNs(configPath)).toBe(before)
    expect(readFileSync(configPath, 'utf-8')).toBe('// hand written\nProjName = "custom";\n')
    // …but the .msxproj itself still records the change.
    expect(loadProject(opened.root)?.project.target).toBe('DOS2')
  })
})

describe('per-project IDE state', () => {
  it('writes and reads .msxdevstudio/state.json, tolerating a missing file', () => {
    const root = makeTmpDir('msxproj-ide-')
    expect(readIdeState(root)).toBeNull()
    writeIdeState(root, { openPaths: ['main.c', 'content/tiles.h'], activePath: 'main.c' })
    expect(readIdeState(root)).toEqual({ openPaths: ['main.c', 'content/tiles.h'], activePath: 'main.c' })
  })
})

describe('scanLibModules', () => {
  it.runIf(hasMsxgl)('lists top-level engine modules and dir/name entries', () => {
    const modules = scanLibModules(REAL_MSXGL)
    expect(modules).toContain('system')
    expect(modules).toContain('bios')
    expect(modules).toContain('vdp')
    expect(modules).toContain('ayfx/ayfx_player')
    expect(modules).toContain('pt3/pt3_player')
    expect(modules).not.toContain('msxgl') // header-only umbrella, no .c
  })

  it('returns an empty list for a folder that is not MSXgl', () => {
    expect(scanLibModules(makeTmpDir('not-msxgl-'))).toEqual([])
  })
})

describe('evaluateProjectConfig (sandboxed child process)', () => {
  it.runIf(hasMsxgl && NODE !== null)(
    "reads the real projects/template/ config chain's effective values",
    async () => {
      const globals = await evaluateProjectConfig(REAL_MSXGL, join(REAL_MSXGL, 'projects/template'), NODE as string)
      expect(globals.ProjName).toBe('template')
      expect(globals.Machine).toBe('1')
      expect(globals.Target).toBe('ROM_32K')
      expect(globals.LibModules).toEqual(['system', 'bios', 'vdp', 'print', 'input', 'memory'])
      expect(globals.CheckVersion).toBe(true)
      // Untouched by the template — comes from setup_global.js's defaults.
      expect(globals.DiskSize).toBe('720K')
      expect(globals.CustomISR).toBe('VBLANK')
    },
    30_000
  )

  it.runIf(hasMsxgl && NODE !== null)(
    'reads projects/template_msx2/ (Machine 2, signature on)',
    async () => {
      const globals = await evaluateProjectConfig(REAL_MSXGL, join(REAL_MSXGL, 'projects/template_msx2'), NODE as string)
      expect(globals.Machine).toBe('2')
      expect(globals.AddROMSignature).toBe(true)
      expect(globals.CompileComplexity).toBe('Default')
    },
    30_000
  )

  it.runIf(hasMsxgl && NODE !== null)('rejects a folder with no project_config.js', async () => {
    await expect(evaluateProjectConfig(REAL_MSXGL, makeTmpDir('msxproj-empty-'), NODE as string)).rejects.toThrow(
      /Could not evaluate project_config.js/
    )
  }, 30_000)

  it.runIf(hasMsxgl && NODE !== null)(
    'replays a per-sample override on top of a shared project_config.js (Spec 12 samples/)',
    async () => {
      const samples = join(REAL_MSXGL, 'projects/samples')

      // Without an override, only the shared project_config.js's own defaults come through.
      const shared = await evaluateProjectConfig(REAL_MSXGL, samples, NODE as string)
      expect(shared.Target).toBe('ROM_32K')

      // `s_mapper.js` mirrors build.js's `projname=s_mapper` CLI override.
      const globals = await evaluateProjectConfig(REAL_MSXGL, samples, NODE as string, 's_mapper.js')
      expect(globals.Machine).toBe('1')
      expect(globals.Target).toBe('ROM_ASCII8')
      expect(globals.ROMSize).toBe(128)
      expect(globals.LibModules).toEqual(['bios', 'system', 'vdp', 'print', 'input', 'memory'])
    },
    30_000
  )
})

describe('importProject', () => {
  it.runIf(hasMsxgl && NODE !== null)(
    'imports a copy of projects/template/ as a customConfig project',
    async () => {
      const root = join(makeTmpDir('msxproj-import-'), 'template')
      cpSync(join(REAL_MSXGL, 'projects/template'), root, { recursive: true })
      const configBefore = mtimeNs(join(root, 'project_config.js'))

      const opened = await importProject(root, REAL_MSXGL, NODE as string)

      expect(opened.imported).toBe(true)
      expect(opened.projectFile).toBe('template.msxproj')
      expect(opened.project.machine).toBe('1')
      expect(opened.project.target).toBe('ROM_32K')
      expect(opened.project.libModules).toEqual(['system', 'bios', 'vdp', 'print', 'input', 'memory'])
      expect(opened.project.customConfig).toBe(true)
      // The hand-written config stays authoritative and untouched.
      expect(mtimeNs(join(root, 'project_config.js'))).toBe(configBefore)
    },
    30_000
  )
})

describe('end-to-end build', () => {
  it.runIf(hasMsxgl && NODE !== null)(
    'builds a wizard-created project into a 32 KB ROM with the real MSXgl toolchain',
    () => {
      const location = makeTmpDir('msxproj-build-')
      const opened = createProject(
        {
          name: 'e2egame',
          location,
          machine: '1',
          target: 'ROM_32K',
          libModules: ['system', 'bios', 'vdp', 'print', 'input', 'memory']
        },
        REAL_MSXGL
      )

      const result = spawnSync(NODE as string, [join(REAL_MSXGL, 'engine/script/js/build.js'), 'all'], {
        cwd: opened.root,
        encoding: 'utf-8'
      })

      const rom = join(opened.root, 'emul/rom/e2egame.rom')
      expect(existsSync(rom), `build failed (exit ${result.status}):\n${result.stdout}\n${result.stderr}`).toBe(true)
      expect(statSync(rom).size).toBe(32768)
    },
    600_000
  )

  it.runIf(hasMsxgl && process.platform !== 'win32')(
    'the generated build.sh runs from a plain shell',
    () => {
      const location = makeTmpDir('msxproj-sh-')
      const opened = createProject(
        { name: 'shgame', location, machine: '1', target: 'ROM_32K', libModules: ['system'] },
        REAL_MSXGL
      )
      // `none` disables every build step: enough to prove the launcher finds node + build.js.
      const result = spawnSync('./build.sh', ['none'], { cwd: opened.root, encoding: 'utf-8' })
      expect(result.status, `${result.stdout}\n${result.stderr}`).toBe(0)
    },
    120_000
  )
})
