/**
 * Project files on disk: scaffolding a new project from the MSXgl template,
 * loading/saving `.msxproj` (and regenerating `project_config.js` from it),
 * per-project IDE state, the LibModules scan, and the sandboxed evaluator
 * that reads an existing MSXgl project's effective config.
 *
 * Electron-free on purpose (same split as `toolchain.ts` /
 * `toolchain-service.ts`) so all of it is directly unit-testable.
 */

import { spawn } from 'node:child_process'
import {
  chmodSync,
  copyFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync
} from 'node:fs'
import { tmpdir } from 'node:os'
import { basename, dirname, join } from 'node:path'
import type { NewProjectRequest, OpenProject } from '../../shared/ipc'
import {
  generateProjectConfig,
  IMPORTED_CONFIG_KEYS,
  normalizeProject,
  projectFromConfigGlobals,
  type ConfigGlobals,
  type MsxProject
} from '../../shared/msxproj'
import { RESOURCE_DIR } from '../../shared/msx/resource'
import type { ProjectTabsState } from '../../shared/tabs'

export const PROJECT_EXT = '.msxproj'
export const IDE_STATE_DIR = '.msxstudio'
export const CONFIG_FILE = 'project_config.js'

/** The `.msxproj` in `dir`, if any (root-relative filename). */
export function findProjectFile(dir: string): string | null {
  const entries = readdirSync(dir, { withFileTypes: true }).filter(
    (e) => e.isFile() && e.name.endsWith(PROJECT_EXT)
  )
  return entries[0]?.name ?? null
}

/** Regenerates `project_config.js` — unless the user claimed ownership of it. */
export function writeGeneratedConfig(root: string, projectFile: string, project: MsxProject): void {
  if (project.customConfig) return
  writeFileSync(join(root, CONFIG_FILE), generateProjectConfig(project, projectFile), 'utf-8')
}

export function saveProject(root: string, projectFile: string, project: MsxProject): OpenProject {
  writeFileSync(join(root, projectFile), `${JSON.stringify(project, null, 2)}\n`, 'utf-8')
  writeGeneratedConfig(root, projectFile, project)
  return { root, projectFile, project, imported: false }
}

/** Loads an existing `.msxproj` from `root`. Null when there is none. */
export function loadProject(root: string): OpenProject | null {
  const projectFile = findProjectFile(root)
  if (!projectFile) return null
  const raw = JSON.parse(readFileSync(join(root, projectFile), 'utf-8')) as unknown
  const project = normalizeProject(raw, basename(projectFile, PROJECT_EXT))
  return { root, projectFile, project, imported: false }
}

// ── new project ─────────────────────────────────────────────────────────────

/** MSX1 keeps the plain template; everything newer gets the MSX2 one. */
export function templateDirFor(machine: string): string {
  return machine === '1' ? 'template' : 'template_msx2'
}

/** Exported for the examples browser's fork (Spec 12) — a forked sample needs the same launchers. */
export function launcherScripts(msxglPath: string): { name: string; content: string; exec: boolean }[] {
  const posix = msxglPath.split('\\').join('/')
  const win = msxglPath.split('/').join('\\')
  return [
    {
      name: 'build.sh',
      exec: true,
      content: `#!/bin/sh\n# GENERATED by MSXStudio — set MSXGL_PATH to build against another MSXgl checkout.\nMSXGL_PATH="\${MSXGL_PATH:-${posix}}"\nexec "$MSXGL_PATH/tools/build/Node/node" "$MSXGL_PATH/engine/script/js/build.js" "$@"\n`
    },
    {
      name: 'build.bat',
      exec: false,
      content: `@echo off\r\nREM GENERATED by MSXStudio — set MSXGL_PATH to build against another MSXgl checkout.\r\nif not defined MSXGL_PATH set MSXGL_PATH=${win}\r\n"%MSXGL_PATH%\\tools\\build\\Node\\node.exe" "%MSXGL_PATH%\\engine\\script\\js\\build.js" %*\r\n`
    }
  ]
}

/**
 * Creates `<location>/<name>/` from the MSXgl template: `main.c` and
 * `msxgl_config.h` copied verbatim, a generated `project_config.js`, the
 * `.msxproj`, empty `content/` and `res/` folders, `.gitignore`, and terminal
 * launchers.
 */
export function createProject(request: NewProjectRequest, msxglPath: string): OpenProject {
  const root = join(request.location, request.name)
  if (existsSync(root) && readdirSync(root).length > 0) {
    throw new Error(`"${root}" already exists and is not empty`)
  }

  const template = join(msxglPath, 'projects', templateDirFor(request.machine))
  if (!existsSync(join(template, 'template.c'))) {
    throw new Error(`MSXgl template not found at ${template}`)
  }

  mkdirSync(join(root, 'content'), { recursive: true })
  // Generated headers land in content/, editor resources in res/ — see RESOURCE_DIR.
  mkdirSync(join(root, RESOURCE_DIR), { recursive: true })
  copyFileSync(join(template, 'template.c'), join(root, 'main.c'))
  copyFileSync(join(template, 'msxgl_config.h'), join(root, 'msxgl_config.h'))
  writeFileSync(join(root, '.gitignore'), `out/\nemul/\n${IDE_STATE_DIR}/\n`, 'utf-8')

  for (const script of launcherScripts(msxglPath)) {
    const path = join(root, script.name)
    writeFileSync(path, script.content, 'utf-8')
    if (script.exec) chmodSync(path, 0o755)
  }

  const project = normalizeProject(
    { name: request.name, machine: request.machine, target: request.target, libModules: request.libModules },
    request.name
  )
  return saveProject(root, `${request.name}${PROJECT_EXT}`, project)
}

// ── per-project IDE state (.msxstudio/state.json) ────────────────────────────

function ideStatePath(root: string): string {
  return join(root, IDE_STATE_DIR, 'state.json')
}

export function readIdeState(root: string): ProjectTabsState | null {
  try {
    return JSON.parse(readFileSync(ideStatePath(root), 'utf-8')) as ProjectTabsState
  } catch {
    return null
  }
}

export function writeIdeState(root: string, state: ProjectTabsState): void {
  const path = ideStatePath(root)
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, JSON.stringify(state, null, 2), 'utf-8')
}

// ── LibModules ──────────────────────────────────────────────────────────────

const libModuleCache = new Map<string, string[]>()

/** Every `LibModules` candidate in `<msxgl>/engine/src/`: `name` and `dir/name`. Cached per root. */
export function scanLibModules(msxglPath: string): string[] {
  const cached = libModuleCache.get(msxglPath)
  if (cached) return cached

  const srcDir = join(msxglPath, 'engine', 'src')
  const modules: string[] = []
  const collect = (dir: string, prefix: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.isFile() && entry.name.endsWith('.c')) modules.push(prefix + entry.name.slice(0, -2))
      else if (entry.isDirectory() && !prefix) collect(join(dir, entry.name), `${entry.name}/`)
    }
  }
  try {
    collect(srcDir, '')
  } catch {
    return []
  }
  modules.sort()
  libModuleCache.set(msxglPath, modules)
  return modules
}

// ── sandboxed config evaluation (import) ────────────────────────────────────

const JSON_MARKER = '@@MSXSTUDIO_CONFIG@@'

/**
 * Runs in a *child* Node process — never in main. It replays MSXgl's own
 * config chain (setup_global → projects/default_config → project_config →
 * optional per-sample override) and prints the resulting globals, so template
 * literals, spreads and any other JS in a hand-written config are evaluated
 * exactly as the build tool does.
 *
 * The optional 4th arg mirrors build.js's own sub-project override: a
 * `projname=<id>` CLI arg sets `ProjName` before it conditionally requires
 * `<ProjName>.js` — that's how `projects/samples/` hosts 56 projects behind
 * one shared `project_config.js` (Spec 12's examples browser).
 */
const DUMPER_SOURCE = `
const fs = require('fs'), path = require('path');
const [root, projDir, keysJson, overrideFile] = process.argv.slice(2);
require(path.join(root, 'engine/script/js/setup_global.js'));
global.ProjDir = projDir.split('\\\\').join('/') + '/';
const userDefaults = path.join(root, 'projects/default_config.js');
if (fs.existsSync(userDefaults)) require(userDefaults);
require(path.join(projDir, 'project_config.js'));
if (overrideFile) {
	global.ProjName = path.basename(overrideFile, '.js');
	const overridePath = path.join(projDir, overrideFile);
	if (fs.existsSync(overridePath)) require(overridePath);
}
const out = {};
for (const key of JSON.parse(keysJson)) out[key] = global[key];
process.stdout.write('\\n${JSON_MARKER}' + JSON.stringify(out));
`

/** Path to the Node that runs MSXgl's scripts: the override, else MSXgl's bundled one. */
export function resolveNodeBinary(msxglPath: string, override?: string | null): string | null {
  if (override && existsSync(override)) return override
  const bundled = join(msxglPath, 'tools', 'build', 'Node', process.platform === 'win32' ? 'node.exe' : 'node')
  return existsSync(bundled) ? bundled : null
}

export function evaluateProjectConfig(
  msxglPath: string,
  projectDir: string,
  nodeBinary: string,
  /** Basename of a per-sample override file (e.g. `s_hello.js`), required by `projectDir`'s
   *  own `project_config.js` before `require`ing it — Spec 12's examples browser only. */
  overrideFile?: string
): Promise<ConfigGlobals> {
  const scratch = mkdtempSync(join(tmpdir(), 'msxstudio-cfg-'))
  const script = join(scratch, 'dump.cjs')
  writeFileSync(script, DUMPER_SOURCE, 'utf-8')

  return new Promise((resolve, reject) => {
    const child = spawn(
      nodeBinary,
      [script, msxglPath, projectDir, JSON.stringify(IMPORTED_CONFIG_KEYS), overrideFile ?? ''],
      { cwd: projectDir, timeout: 15_000 }
    )
    let stdout = ''
    let stderr = ''
    child.stdout.on('data', (chunk: Buffer) => (stdout += chunk.toString('utf-8')))
    child.stderr.on('data', (chunk: Buffer) => (stderr += chunk.toString('utf-8')))
    child.on('error', (error) => {
      rmSync(scratch, { recursive: true, force: true })
      reject(error)
    })
    child.on('close', (code) => {
      rmSync(scratch, { recursive: true, force: true })
      const marker = stdout.lastIndexOf(JSON_MARKER)
      if (marker === -1) {
        reject(new Error(`Could not evaluate project_config.js (exit ${code}): ${stderr || stdout}`))
        return
      }
      resolve(JSON.parse(stdout.slice(marker + JSON_MARKER.length)) as ConfigGlobals)
    })
  })
}

/**
 * Imports a pre-existing MSXgl project: evaluates its config chain and writes
 * a `.msxproj` beside it with `customConfig: true`, so the hand-written
 * `project_config.js` stays authoritative until the user opts in.
 */
export async function importProject(
  root: string,
  msxglPath: string,
  nodeBinary: string
): Promise<OpenProject> {
  const globals = await evaluateProjectConfig(msxglPath, root, nodeBinary)
  const project = { ...projectFromConfigGlobals(globals, basename(root)), customConfig: true }
  const saved = saveProject(root, `${project.name}${PROJECT_EXT}`, project)
  return { ...saved, imported: true }
}

export function hasMsxglConfig(root: string): boolean {
  return existsSync(join(root, CONFIG_FILE))
}
