// monaco-editor's package.json "exports" map already redirects `./*` to
// `./esm/vs/*.js`, so the subpath here must exclude the `esm/vs` prefix.
import EditorWorker from 'monaco-editor/editor/editor.worker?worker'
import JsonWorker from 'monaco-editor/language/json/json.worker?worker'

let configured = false

// Spec 13: `monaco-models.ts`/`MonacoEditorTab.vue`/etc. now import
// `./monaco-full` (generated by `scripts/generate-monaco-shim.mjs`, `npm run
// monaco:shim`) instead of the bare `monaco-editor` package. That entry point
// registers every bundled language as lazy code-split chunks (cheap, fine to
// keep) but also eagerly pulls in the css/html/typescript "rich language"
// features, each bundling its own multi-megabyte language-server worker
// (ts.worker.js alone is ~13MB) — ~16MB of dead weight in the packaged app
// for languages this IDE never edits. See the generator script for the
// trimmed list.

/**
 * Wires Monaco's web workers via Vite's plain `?worker` imports — preferred
 * over adding a bundler plugin (e.g. vite-plugin-monaco-editor) for this.
 * Only `json` needs its own worker for the languages this spec supports (c/h,
 * asm/s as plaintext, markdown have no language-service worker); everything
 * else falls back to the generic editor worker.
 */
export function setupMonacoEnvironment(): void {
  if (configured) return
  configured = true
  self.MonacoEnvironment = {
    getWorker(_workerId: string, label: string) {
      if (label === 'json') return new JsonWorker()
      return new EditorWorker()
    }
  }
}
