import { describe, expect, it } from 'vitest'
import {
  defaultProject,
  generateProjectConfig,
  normalizeProject,
  projectFromConfigGlobals,
  type MsxProject
} from './msxproj'
import { isMappedRomTarget, resolveTarget } from './msxgl-consts'

function project(overrides: (p: MsxProject) => void = () => {}): MsxProject {
  const p = defaultProject('mygame')
  overrides(p)
  return p
}

describe('generateProjectConfig', () => {
  it('renders a default project, omitting everything MSXgl already defaults to', () => {
    expect(generateProjectConfig(project(), 'mygame.msxproj')).toMatchInlineSnapshot(`
      "// GENERATED by MSXStudio from mygame.msxproj — edit settings in the IDE, or set
      // "customConfig": true to hand-edit this file.

      //-- Project
      ProjName = "mygame";
      ProjModules = ["main"];
      LibModules = ["system", "bios", "vdp", "print", "input", "memory"];

      //-- Target
      Machine = "1";
      Target = "ROM_32K";
      CheckVersion = true;
      "
    `)
  })

  it('changes exactly the target lines when the target becomes a mapped ROM', () => {
    const before = generateProjectConfig(project(), 'mygame.msxproj')
    const after = generateProjectConfig(
      project((p) => {
        p.target = 'ROM_ASCII8'
        p.romSize = 128
      }),
      'mygame.msxproj'
    )
    const added = after.split('\n').filter((line) => !before.includes(line))
    const removed = before.split('\n').filter((line) => !after.includes(line))
    expect(added).toEqual(['Target = "ROM_ASCII8";', 'ROMSize = 128;'])
    expect(removed).toEqual(['Target = "ROM_32K";'])
  })

  it('ignores romSize on non-mapped targets', () => {
    const text = generateProjectConfig(
      project((p) => {
        p.romSize = 512
      }),
      'mygame.msxproj'
    )
    expect(text).not.toContain('ROMSize')
  })

  it('writes every non-default setting across all sections', () => {
    const text = generateProjectConfig(
      project((p) => {
        p.machine = '2'
        p.target = 'ROM_KONAMI_SCC'
        p.romSize = 256
        p.build.optim = 'Size'
        p.build.debug = true
        p.build.allowUndocumented = true
        p.build.compileComplexity = 'Ultra'
        p.build.defines = { DEBUG_LEVEL: '2' }
        p.rom.checkVersion = false
        p.rom.delayBoot = true
        p.rom.signature = true
        p.rom.installRamIsr = 'RAMISR_PAGE3'
        p.rom.customIsr = 'ALL'
        p.rom.bankedCall = true
        p.files.rawFiles = [{ offset: 0x8000, file: 'data/tiles.bin' }, { page: 2, file: 'data/map.bin' }]
        p.files.diskFiles = ['data/level1.dat']
        p.files.diskSize = '360K'
        p.emulator.ext.scc = true
        p.emulator.portA = 'Joystick'
        p.emulator.hz60 = true
        p.emulator.openmsxMachine = 'Philips_NMS_8250'
      }),
      'mygame.msxproj'
    )

    expect(text).toContain('Machine = "2";')
    expect(text).toContain('Target = "ROM_KONAMI_SCC";')
    expect(text).toContain('ROMSize = 256;')
    expect(text).not.toContain('CheckVersion') // back to MSXgl's own default (false)
    expect(text).toContain('ROMDelayBoot = true;')
    expect(text).toContain('AddROMSignature = true;')
    expect(text).toContain('InstallRAMISR = "RAMISR_PAGE3";')
    expect(text).toContain('CustomISR = "ALL";')
    expect(text).toContain('BankedCall = true;')
    expect(text).toContain('Optim = "Size";')
    expect(text).toContain('CompileComplexity = "Ultra";')
    expect(text).toContain('Debug = true;')
    expect(text).toContain('AllowUndocumented = true;')
    expect(text).toContain('RawFiles = [ { offset:0x8000, file:"data/tiles.bin" }, { page:2, file:"data/map.bin" } ];')
    expect(text).toContain('DiskFiles = ["data/level1.dat"];')
    expect(text).toContain('DiskSize = "360K";')
    expect(text).toContain('EmulSCC = true;')
    expect(text).toContain('EmulPortA = "Joystick";')
    expect(text).toContain('Emul60Hz = true;')
    // An explicit openMSX machine replaces MSXgl's generated -machine C-BIOS_… argument.
    expect(text).toContain('EmulMachine = false;')
    expect(text).toContain('EmulExtraParam = "-machine Philips_NMS_8250";')
    // defines are build-time CLI args (Spec 04), never config settings.
    expect(text).not.toContain('DEBUG_LEVEL')
  })

  it('always carries the GENERATED banner naming the source .msxproj', () => {
    expect(generateProjectConfig(project(), 'other.msxproj')).toContain(
      '// GENERATED by MSXStudio from other.msxproj'
    )
  })

  it('resolves target aliases the way setup_target.js does', () => {
    expect(generateProjectConfig(project((p) => (p.target = 'rom')), 'x.msxproj')).toContain('Target = "ROM_32K";')
    expect(generateProjectConfig(project((p) => (p.target = 'DOS')), 'x.msxproj')).toContain('Target = "DOS1";')
  })
})

describe('normalizeProject', () => {
  it('fills in every missing section of a minimal .msxproj', () => {
    const p = normalizeProject({ name: 'tiny', target: 'DOS1' }, 'fallback')
    expect(p.name).toBe('tiny')
    expect(p.target).toBe('DOS1')
    expect(p.machine).toBe('1')
    expect(p.rom.customIsr).toBe('VBLANK')
    expect(p.emulator.ext.scc).toBe(false)
    expect(p.files.diskSize).toBe('720K')
  })

  it('falls back to the file-derived name and survives junk input', () => {
    expect(normalizeProject(null, 'fromfile').name).toBe('fromfile')
    expect(normalizeProject({ name: '' }, 'fromfile').name).toBe('fromfile')
  })

  it('coerces hand-edited imgRules into well-formed entries (Spec 07)', () => {
    const p = normalizeProject(
      {
        name: 'x',
        resources: {
          imgRules: [
            { input: 'a.png', out: 'content/a.h', args: ['-bpc', 4] },
            { input: 'b.png' },
            'nonsense',
            null
          ]
        }
      } as never,
      'x'
    )
    expect(p.resources.imgRules).toEqual([
      { input: 'a.png', out: 'content/a.h', args: ['-bpc', '4'] },
      { input: 'b.png', out: '', args: [] }
    ])
    expect(normalizeProject({ name: 'x' }, 'x').resources.imgRules).toEqual([])
  })
})

describe('projectFromConfigGlobals', () => {
  it('maps evaluated MSXgl globals onto a project', () => {
    const p = projectFromConfigGlobals(
      {
        ProjName: 'imported',
        Machine: '2',
        Target: 'ROM_ASCII8',
        ROMSize: 512,
        LibModules: ['system', 'vdp'],
        ProjModules: ['imported'],
        CheckVersion: true,
        Optim: 'Size',
        DiskSize: '360K',
        EmulSCC: true,
        EmulPortA: 'JOYSTICK'
      },
      'folder'
    )
    expect(p.name).toBe('imported')
    expect(p.machine).toBe('2')
    expect(p.target).toBe('ROM_ASCII8')
    expect(p.romSize).toBe(512)
    expect(p.libModules).toEqual(['system', 'vdp'])
    expect(p.rom.checkVersion).toBe(true)
    expect(p.build.optim).toBe('Size')
    expect(p.files.diskSize).toBe('360K')
    expect(p.emulator.ext.scc).toBe(true)
    expect(p.emulator.portA).toBe('JOYSTICK')
  })

  it('drops ROMSize for non-mapped targets and falls back to the folder name', () => {
    const p = projectFromConfigGlobals({ Target: 'ROM_32K', ROMSize: 128 }, 'folder')
    expect(p.name).toBe('folder')
    expect(p.romSize).toBeNull()
  })
})

describe('target helpers', () => {
  it('resolves the aliases setup_target.js defines', () => {
    expect(resolveTarget('rom')).toBe('ROM_32K')
    expect(resolveTarget('bin')).toBe('BIN_DISK')
    expect(resolveTarget('ROM_K5')).toBe('ROM_KONAMI_SCC')
    expect(resolveTarget('ROM_32K')).toBe('ROM_32K')
  })

  it('knows which targets take a ROMSize', () => {
    expect(isMappedRomTarget('ROM_ASCII8')).toBe(true)
    expect(isMappedRomTarget('rom_k4')).toBe(true)
    expect(isMappedRomTarget('ROM_32K')).toBe(false)
  })
})
