// Generated by MSXStudio — do not edit by hand.
// Edit the source resource and re-export (or press Build) instead.
//
// Generation parameters:
//  - Source: res/player.sprites.json
//  - Sprite mode: 1
//  - Size: 16×16
//  - Characters: 1

#pragma once

#define G_PLAYERSPRITES_PLAYER_BASE 0
#define G_PLAYERSPRITES_PLAYER_PLANES 3
#define G_PLAYERSPRITES_PLAYER_FRAMES 6

#define G_PLAYERSPRITES_PATTERNS_SIZE 576
extern const unsigned char g_PlayerSprites_Patterns[];

#define G_PLAYERSPRITES_COLORS_SIZE 18
extern const unsigned char g_PlayerSprites_Colors[];

#define G_PLAYERSPRITES_LAYOUT_SIZE 36
extern const unsigned char g_PlayerSprites_Layout[];


// Places one character of g_PlayerSprites as a group of hardware sprites, from a single
// coordinate. Needs MSXgl's VDP module (#include "msxgl.h" before this header),
// and the patterns loaded at VRAM pattern 0:
//   VDP_LoadSpritePattern(g_PlayerSprites_Patterns, 0, G_PLAYERSPRITES_PATTERNS_SIZE / 8);
//
// Parameters:
//   index  - first hardware sprite plane to write [0:31]
//   x, y   - screen position of the character's top-left corner
//   base   - first plane of the frame to show: G_PLAYERSPRITES_<CHARACTER>_BASE + frame * ..._PLANES
//   planes - ..._PLANES for that character
void g_PlayerSprites_SetMeta(u8 index, u8 x, u8 y, u8 base, u8 planes);
