// Generated by MSXStudio — do not edit by hand.
// Edit the source resource and re-export (or press Build) instead.
//
// Generation parameters:
//  - Source: res/tiles.tiles.json
//  - Mode: SCREEN 2 (GRAPHIC 2)
//  - Tiles: 68
//  - Blocks: coin_spin 4×1, door_open 1×2, building 2×2, pine tree 2×2, big_cloud 3×1
//  - Flagged tiles: 12

#pragma once

#define G_TILES_COIN_SPIN_BASE 0
#define G_TILES_COIN_SPIN_W 4
#define G_TILES_COIN_SPIN_H 1
#define G_TILES_DOOR_OPEN_BASE 4
#define G_TILES_DOOR_OPEN_W 1
#define G_TILES_DOOR_OPEN_H 2
#define G_TILES_BUILDING_BASE 6
#define G_TILES_BUILDING_W 2
#define G_TILES_BUILDING_H 2
#define G_TILES_PINE_TREE_BASE 10
#define G_TILES_PINE_TREE_W 2
#define G_TILES_PINE_TREE_H 2
#define G_TILES_BIG_CLOUD_BASE 14
#define G_TILES_BIG_CLOUD_W 3
#define G_TILES_BIG_CLOUD_H 1

#define G_TILES_PATTERNS_SIZE 544
extern const unsigned char g_Tiles_Patterns[];

#define G_TILES_COLORS_SIZE 544
extern const unsigned char g_Tiles_Colors[];

#define G_TILES_FLAGS_SIZE 68
extern const unsigned char g_Tiles_Flags[];

#define G_TILES_BLOCKS_SIZE 17
extern const unsigned char g_Tiles_Blocks[];


// Stamps one block of g_Tiles into the name table at tile column/row (x, y).
// Needs MSXgl's VDP module (#include "msxgl.h" before this header) built
// with VDP_USE_MODE_G2 or VDP_USE_MODE_G3.
//
// Example:
//   g_Tiles_DrawBlock(10, 5, G_TILES_COIN_SPIN_BASE, G_TILES_COIN_SPIN_W, G_TILES_COIN_SPIN_H);
void g_Tiles_DrawBlock(u8 x, u8 y, u16 base, u8 w, u8 h);
