// Generated by MSXStudio — do not edit by hand.
// Edit the source resource and re-export (or press Build) instead.
//
// Generation parameters:
//  - Source: res/boss.screen.json
//  - Mode: SCREEN 5 (GRAPHIC 4)
//  - Dither: bayer4
//  - Fragments: rest 68×40, flex 68×40

#pragma once

#define G_BOSS_W 136
#define G_BOSS_H 40
#define G_BOSS_STRIP_W 136
#define G_BOSS_STRIP_H 40
#define G_BOSS_BACKUP_PITCH 72
#define G_BOSS_REST 0
#define G_BOSS_FLEX 1

#define G_BOSS_PALETTE_SIZE 32
extern const unsigned char g_Boss_Palette[];

#define G_BOSS_DATA_SIZE 2720
extern const unsigned char g_Boss_Data[];

#define G_BOSS_STRIP_SIZE 2720
extern const unsigned char g_Boss_Strip[];

#define G_BOSS_RECTS_SIZE 8
extern const unsigned char g_Boss_Rects[];


// ── g_Boss: software sprites ─────────────────────────────────────────
//
// Software sprites are drawn *into* the screen, so they escape the VDP's
// 4/8-sprites-per-line limit — at the price of putting back what they
// covered. The frames live side by side in g_Boss_Strip; upload it once
// into VRAM the screen never shows (below the visible lines is the usual
// spot), then move each object with Restore/Draw.
//
// Needs MSXgl's VDP command engine: MSX2 or later with VDP_USE_COMMAND,
// and "msxgl.h" included before this header.
//
// Two rules:
//  - Give every object its own slot (0, 1, 2 …). Backgrounds are saved
//    side by side in the row under the strip, G_BOSS_BACKUP_PITCH dots apart,
//    and two objects sharing a slot would eat each other's background.
//  - When objects can overlap, Restore them all in *reverse* draw order
//    first, then Draw them all in order. Restoring one at a time rubs out
//    whatever was drawn on top of it.
//
// Example:
//   g_Boss_Upload(212);                  // strip parked at VRAM row 212
//   g_Boss_SwSprite hero = { 0 };        // slot 0
//   // every frame:
//   g_Boss_Restore(&hero, 212);
//   g_Boss_Draw(&hero, G_BOSS_REST, x, y, 212);
typedef struct
{
	u8  slot; // which backup column this object owns
	UX  bx;   // the saved background rectangle; bw = 0 means nothing is on screen
	UY  by;
	u8  bw, bh;
} g_Boss_SwSprite;

void g_Boss_Upload(UY stripY);
void g_Boss_Restore(g_Boss_SwSprite* s, UY stripY);
void g_Boss_Draw(g_Boss_SwSprite* s, u8 frame, UX x, UY y, UY stripY);
