// Generated by MSXStudio — do not edit by hand.
// Edit the source resource and re-export (or press Build) instead.
//
// Generation parameters:
//  - Source: res/fleet.sprites.json
//  - Sprite mode: 2
//  - Size: 16×16
//  - Characters: 4

#pragma once

#define G_FLEET_SHIP_COPY_BASE 0
#define G_FLEET_SHIP_COPY_PLANES 2
#define G_FLEET_SHIP_COPY_FRAMES 2
#define G_FLEET_SHOT_BASE 4
#define G_FLEET_SHOT_PLANES 1
#define G_FLEET_SHOT_FRAMES 1
#define G_FLEET_DRONE_BASE 5
#define G_FLEET_DRONE_PLANES 1
#define G_FLEET_DRONE_FRAMES 2
#define G_FLEET_BOOM_BASE 7
#define G_FLEET_BOOM_PLANES 1
#define G_FLEET_BOOM_FRAMES 3

#define G_FLEET_PATTERNS_SIZE 320
extern const unsigned char g_Fleet_Patterns[];

#define G_FLEET_COLORS_SIZE 160
extern const unsigned char g_Fleet_Colors[];

#define G_FLEET_PALETTE_SIZE 32
extern const unsigned char g_Fleet_Palette[];

#define G_FLEET_LAYOUT_SIZE 20
extern const unsigned char g_Fleet_Layout[];


// Places one character of g_Fleet as a group of hardware sprites, from a single
// coordinate. Needs MSXgl's VDP module (#include "msxgl.h" before this header),
// and the patterns loaded at VRAM pattern 0:
//   VDP_LoadSpritePattern(g_Fleet_Patterns, 0, G_FLEET_PATTERNS_SIZE / 8);
//
// Parameters:
//   index  - first hardware sprite plane to write [0:31]
//   x, y   - screen position of the character's top-left corner
//   base   - first plane of the frame to show: G_FLEET_<CHARACTER>_BASE + frame * ..._PLANES
//   planes - ..._PLANES for that character
void g_Fleet_SetMeta(u8 index, u8 x, u8 y, u8 base, u8 planes);
