// Generated by MSXStudio — do not edit by hand.
// Edit the source resource and re-export (or press Build) instead.
//
// Generation parameters:
//  - Source: res/hud.screen.json
//  - Mode: SCREEN 5 (GRAPHIC 4)
//  - Dither: none
//  - Fragments: bar3 40×16, bar2 40×16, bar1 40×16, bar0 40×16, life0 16×16, life1 16×16, life2 16×16, life3 16×16

#pragma once

#define G_HUD_W 224
#define G_HUD_H 16
#define G_HUD_STRIP_W 224
#define G_HUD_STRIP_H 16
#define G_HUD_BACKUP_PITCH 44
#define G_HUD_BAR3 0
#define G_HUD_BAR2 1
#define G_HUD_BAR1 2
#define G_HUD_BAR0 3
#define G_HUD_LIFE0 4
#define G_HUD_LIFE1 5
#define G_HUD_LIFE2 6
#define G_HUD_LIFE3 7

#define G_HUD_PALETTE_SIZE 32
extern const unsigned char g_Hud_Palette[];

#define G_HUD_STRIP_SIZE 1792
extern const unsigned char g_Hud_Strip[];

#define G_HUD_RECTS_SIZE 32
extern const unsigned char g_Hud_Rects[];


// ── g_Hud: software sprites ─────────────────────────────────────────
//
// Software sprites are drawn *into* the screen, so they escape the VDP's
// 4/8-sprites-per-line limit — at the price of putting back what they
// covered. The frames live side by side in g_Hud_Strip; upload it once
// into VRAM the screen never shows (below the visible lines is the usual
// spot), then move each object with Restore/Draw.
//
// Needs MSXgl's VDP command engine: MSX2 or later with VDP_USE_COMMAND,
// and "msxgl.h" included before this header.
//
// Two rules:
//  - Give every object its own slot (0, 1, 2 …). Backgrounds are saved
//    side by side in the row under the strip, G_HUD_BACKUP_PITCH dots apart,
//    and two objects sharing a slot would eat each other's background.
//  - When objects can overlap, Restore them all in *reverse* draw order
//    first, then Draw them all in order. Restoring one at a time rubs out
//    whatever was drawn on top of it.
//
// Example:
//   g_Hud_Upload(212);                  // strip parked at VRAM row 212
//   g_Hud_SwSprite hero = { 0 };        // slot 0
//   // every frame:
//   g_Hud_Restore(&hero, 212);
//   g_Hud_Draw(&hero, G_HUD_BAR3, x, y, 212);
typedef struct
{
	u8  slot; // which backup column this object owns
	UX  bx;   // the saved background rectangle; bw = 0 means nothing is on screen
	UY  by;
	u8  bw, bh;
} g_Hud_SwSprite;

void g_Hud_Upload(UY stripY);
void g_Hud_Restore(g_Hud_SwSprite* s, UY stripY);
void g_Hud_Draw(g_Hud_SwSprite* s, u8 frame, UX x, UY y, UY stripY);
