// Generated by MSXStudio — do not edit by hand.
// Edit the source resource and re-export (or press Build) instead.
//
// Generation parameters:
//  - Source: res/stage.map.json
//  - Tileset: res/canyon.screen.json
//  - Size: 16×160
//  - Layers: terrain
//  - Cell: 16×16 dots, atlas 16 cells per row (bitmap mode — cells are copied, not indexed)

#pragma once

#define G_STAGE_W 16
#define G_STAGE_H 160
#define G_STAGE_CELL_W 16
#define G_STAGE_CELL_H 16
#define G_STAGE_ATLAS_COLS 16

#define G_STAGE_TERRAIN_SIZE 2560
extern const unsigned char g_Stage_Terrain[];


// ── g_Stage: a tilemap in a bitmap mode ───────────────────────────────
//
// Draws map row `row` as 16 cells of 16×16 dots, starting at
// dot column 0 of VRAM row `destY`. Cells come from an atlas image parked
// at (0, `atlasY`) in VRAM — upload it once with a single HMMC:
//
//   VDP_CommandHMMC(g_Atlas, 0, atlasY, ATLAS_W, ATLAS_H);
//
// Cell n is the atlas's nth 16×16 block, read left to right and top to
// bottom, 16 to a row. There is no name table in these modes, so this
// copies pixels: the map is the same bytes it always was, but a cell is a
// rectangle rather than an index the VDP resolves for you.
//
// A vertical scroller calls this for the one row about to scroll into the
// hidden lines below the display, and leaves the rest alone. Mask `destY`
// yourself if you want it to wrap inside a page — the VDP addresses all of
// VRAM as one tall column, so 256 is the next page, not row 0 again.
//
// Needs MSXgl's VDP command engine: MSX2 or later with VDP_USE_COMMAND,
// and "msxgl.h" included before this header.
//
// Example:
//   g_Stage_DrawRow(g_Stage_Terrain, row, ATLAS_Y, (u8)(row * 16));
void g_Stage_DrawRow(const u8* layer, u8 row, UY atlasY, UY destY);
