// MSXgl | Raw files definitions generated by the Build tool

#define ATLAS_BIN_SEG 	4
#define ATLAS_BIN_REL 	0x0000
#define ATLAS_BIN_ABS 	0x8000
#define ATLAS_BIN_SIZE	0x1820

#define TITLE_BIN_ABS 	0x9FE0
#define TITLE_BIN_SIZE	0x6A20

#define CREDITS_BIN_ABS 	0x11FE0
#define CREDITS_BIN_SIZE	0x6A20
