// MSXgl | Raw files definitions generated by the Build tool

#define ATLAS_BIN_ABS 	0x19FE0
#define ATLAS_BIN_SIZE	0x2064

#define ENDINGS_BIN_ABS 	0x9860
#define ENDINGS_BIN_SIZE	0x06E8

#define TITLE_BIN_ABS 	0x9FE0
#define TITLE_BIN_SIZE	0x6A20

#define CREDITS_BIN_ABS 	0x11FE0
#define CREDITS_BIN_SIZE	0x6A20

#define BOSS_BIN_ABS 	0x18A00
#define BOSS_BIN_SIZE	0x0AC8
