// ─────────────────────────────────────────────────────────────────────────────
// The ship and its shots — hardware sprites, and the one place mode 2's
// OR-colour is doing real work.
//
// The ship is two planes on the same coordinate. Plane 0 is the hull, with one
// colour per *line*: pale cyan at the nose, violet through the body, vein
// orange at the tail. Plane 1 carries the canopy and the exhaust with its CC
// bit set, which tells the VDP to OR its colour with the plane in front instead
// of hiding behind it. The sprite sheet's colours were chosen so those ORs land
// where the art wants them:
//
//     canopy   hull 3 (violet)  | 12 (pale cyan) = 15 (white)
//     exhaust  hull 8 (vein A)  |  2 (dark violet) = 10 (vein C)
//
// Two sprites, five colours, no third plane. `g_Fleet_SetMeta` writes both
// planes from one coordinate — it is generated by the sprite editor's exporter.
//
// Every Y here is a *screen* line and goes through `Scroll_SpriteY` on the way
// out, because R#23 scrolls the sprite plane too.
// ─────────────────────────────────────────────────────────────────────────────
#include "canyon.h"

u8 g_ShipX, g_ShipY;

/** Which of the three banked poses is showing, so it is only rewritten on a change. */
static u8 g_Pose;
static u8 g_Cooldown;
/** Frames left of post-hit grace; the ship blinks while it runs. */
static u8 g_Grace;

typedef struct
{
	u8 alive;
	u8 x, y;
} Shot;

static Shot g_Shots[MAX_SHOTS];

#define SHIP_SPEED 2
#define SHOT_SPEED 6
#define SHIP_TOP (PLAY_TOP + 8)
// Clear of the HUD panel: the ship must not add sprites to that line.
#define SHIP_BOTTOM (HUD_Y - 20)
#define FIRE_DELAY 8

void Player_Start(void)
{
	g_ShipX = 120;
	g_ShipY = (u8)(VIEW_H - 48);
	g_Pose = 0xFF;
	g_Cooldown = 0;
	g_Grace = 0;
	g_Energy = MAX_ENERGY;
	for(u8 i = 0; i < MAX_SHOTS; ++i)
	{
		g_Shots[i].alive = 0;
		Scroll_HideSprite(SPR_SHOT + i);
	}
}

void Player_Hide(void)
{
	Scroll_HideSprite(SPR_SHIP);
	Scroll_HideSprite(SPR_SHIP + 1);
	for(u8 i = 0; i < MAX_SHOTS; ++i)
		Scroll_HideSprite(SPR_SHOT + i);
}

static void Fire(void)
{
	for(u8 i = 0; i < MAX_SHOTS; ++i)
	{
		if(g_Shots[i].alive)
			continue;
		g_Shots[i].alive = 1;
		g_Shots[i].x = g_ShipX;
		g_Shots[i].y = g_ShipY - 8;
		g_Cooldown = FIRE_DELAY;
		PlaySfx(0);
		return;
	}
}

/**
 * The canyon walls are solid. The question is asked about the middle of the
 * hull rather than its corners: a 16×16 sprite whose corners are clear of the
 * rock still looks like it is touching it, and the generous version is the one
 * that feels fair.
 */
static bool HitsWall(void)
{
	return IsWall(Scroll_CellAt(g_ShipX + 8, g_ShipY + 8));
}

/**
 * One hit. The grace period is not politeness — without it, a hull resting
 * against rock would spend the whole bar in three frames, and the player would
 * never see what hit them.
 */
void Player_Damage(void)
{
	if(g_Grace)
		return;
	g_Grace = HIT_GRACE;
	PlaySfx(2);
	if(--g_Energy == 0)
		g_State = STATE_DEAD;
}

void Player_Update(void)
{
	u8 pose = 1; // G_FLEET_SHIP, the level pose

	if(Keyboard_IsKeyPressed(KEY_LEFT) && g_ShipX > 4)
	{
		g_ShipX -= SHIP_SPEED;
		pose = 0;
	}
	if(Keyboard_IsKeyPressed(KEY_RIGHT) && g_ShipX < VIEW_W - 20)
	{
		g_ShipX += SHIP_SPEED;
		pose = 2;
	}
	if(Keyboard_IsKeyPressed(KEY_UP) && g_ShipY > SHIP_TOP)
		g_ShipY -= SHIP_SPEED;
	if(Keyboard_IsKeyPressed(KEY_DOWN) && g_ShipY < SHIP_BOTTOM)
		g_ShipY += SHIP_SPEED;

	if(g_Cooldown)
		g_Cooldown--;
	else if(Keyboard_IsKeyPressed(KEY_SPACE))
		Fire();

	// One call places both planes of the pose. The pattern only changes when the
	// ship starts or stops banking, but the position changes every frame, so the
	// call happens every frame either way.
	g_Pose = pose;
	if(g_Grace)
		g_Grace--;
	// Blink through the grace period, so "that hit landed" is visible.
	if(g_Grace && (g_Grace & 4))
	{
		Scroll_HideSprite(SPR_SHIP);
		Scroll_HideSprite(SPR_SHIP + 1);
	}
	else
	{
		g_Fleet_SetMeta(SPR_SHIP, g_ShipX, Scroll_SpriteY(g_ShipY),
			G_FLEET_SHIP_LEFT_BASE + pose * G_FLEET_SHIP_PLANES, G_FLEET_SHIP_PLANES);
	}

	for(u8 i = 0; i < MAX_SHOTS; ++i)
	{
		if(!g_Shots[i].alive)
			continue;
		if(g_Shots[i].y < SHOT_SPEED + PLAY_TOP)
		{
			g_Shots[i].alive = 0;
			Scroll_HideSprite(SPR_SHOT + i);
			continue;
		}
		g_Shots[i].y -= SHOT_SPEED;
		g_Fleet_SetMeta(SPR_SHOT + i, g_Shots[i].x, Scroll_SpriteY(g_Shots[i].y), G_FLEET_SHOT_BASE, G_FLEET_SHOT_PLANES);
	}

	if(HitsWall())
	{
		Player_Damage();
		// Pushed back out of the rock: leaving the hull inside it would spend
		// the next block the moment the grace period ends.
		g_ShipX = (g_ShipX < VIEW_W / 2) ? g_ShipX + 10 : g_ShipX - 10;
	}
}

/** Box overlap against the ship's hull, in screen space. */
u8 Player_HitBy(u8 x, u8 y, u8 w, u8 h)
{
	if(x + w < g_ShipX + 3 || g_ShipX + 13 < x)
		return 0;
	if(y + h < g_ShipY + 3 || g_ShipY + 13 < y)
		return 0;
	return 1;
}

u8 Player_ShotHits(u8 x, u8 y, u8 w, u8 h)
{
	for(u8 i = 0; i < MAX_SHOTS; ++i)
	{
		if(!g_Shots[i].alive)
			continue;
		u8 sx = g_Shots[i].x + 6;
		u8 sy = g_Shots[i].y + 4;
		if(sx < x || sx > x + w || sy < y || sy > y + h)
			continue;
		g_Shots[i].alive = 0;
		Scroll_HideSprite(SPR_SHOT + i);
		return i;
	}
	return MAX_SHOTS;
}
