// GENERATED by MSXStudio from canyon.msxproj — edit settings in the IDE, or set
// "customConfig": true to hand-edit this file.

//-- Project
ProjName = "canyon";
ProjModules = ["main", "scroll", "player", "enemy", "bossfight", "screens", "content/fleet", "content/hud", "content/mist", "content/sfx", "content/stage"];
LibModules = ["system", "bios", "vdp", "keyboard", "memory", "psg", "ayfx/ayfx_player"];

//-- Target
Machine = "2";
Target = "ROM_ASCII8";
ROMSize = 128;
CheckVersion = true;
InstallRAMISR = "RAMISR_PAGE3";
CustomISR = "VHBLANK";

//-- Build
CompileSkipOld = true;

//-- Files
RawFiles = [ { segment:4, file:"data/atlas.bin" }, { offset:0x9820, file:"data/endings.bin" }, { offset:0x9FE0, file:"data/title.bin" }, { offset:0x11FE0, file:"data/credits.bin" }, { offset:0x18A00, file:"data/boss.bin" } ];
