// GENERATED by MSXStudio from demo.msxproj — edit settings in the IDE, or set
// "customConfig": true to hand-edit this file.

//-- Project
ProjName = "demo";
ProjModules = ["main"];
LibModules = ["system", "bios", "vdp", "print", "input", "keyboard", "memory", "psg", "ayfx/ayfx_player", "compress", "sprite_fx"];

//-- Target
Machine = "1";
Target = "ROM_32K";
CheckVersion = true;

//-- Build
CompileSkipOld = true;
