// GENERATED by MSXDEVStudio from demo.msxproj — edit settings in the IDE, or set
// "customConfig": true to hand-edit this file.

//-- Project
ProjName = "demo";
ProjModules = ["main", "level", "view", "player", "screens", "content/background_map", "content/intro_map", "content/intro_tiles", "content/level_map", "content/player_sprites", "content/sfx", "content/tiles"];
LibModules = ["system", "bios", "vdp", "print", "keyboard", "memory", "psg", "ayfx/ayfx_player", "compress", "sprite_fx"];

//-- Target
Machine = "1";
Target = "ROM_32K";
CheckVersion = true;

//-- Build
CompileSkipOld = true;
